clovers-network/clovers-dapp

- app/src/components/Miner.vue
> empty wallets are included in registered wallets

- src/store/actions.js
- src/store/getters.js
- src/store/index.js
`clover_tokens` loaded into state (from `localStorage`), vuex getter returns auth header if signature for current account exists.
> Simple auth state management

- src/components/AppHeader.vue
- src/components/Miner.vue
- src/store/actions.js
- src/store/getters.js
- src/store/index.js
- src/store/mutations.js
> localstorage signin and clover storage

- src/components/AppHeader.vue
- src/components/ToggleBtn.vue
- src/style/helpers.css
- src/style/settings.css
> ToggleBtn Component - props: [active, labels, theme], emits click

- package-lock.json
- src/style/global.css
- src/style/helpers.css
- src/style/icons.css
- src/style/imports.css
- src/style/settings.css
- src/views/Field.vue
- src/views/FieldSingle.vue
> FieldSingle.vue - wireframe

- src/store/getters.js
- src/store/index.js
- src/store/mutations.js
- src/style/global.css
- src/style/helpers.css
- src/views/Field.vue
- src/views/Market.vue
> marketplace filter

- src/components/AppHeader.vue
- src/components/Icons/SymmetryIcons.vue
- src/router.js
- src/store/actions.js
- src/store/mutations.js
- src/style/helpers.css
- src/style/settings.css
- src/utils.js
- src/views/Clover.vue
- src/views/Feed.vue
> Clover.vue (Feed Single)

- src/store/getters.js
- src/views/Clover.vue
- src/views/FieldSingle.vue
> FieldSingle - simplify layout; Getters - userBalance

- src/style/global.css
- src/style/helpers.css
- src/views/Account.vue
> Account - userBalance in ViewNav, update Username layout (centered)

- src/views/Clover.vue
> Clover - owner actions / wireframe

- package-lock.json
- package.json
- vue.config.js
- yarn.lock
Launches a package analyzer alongside, also @n-kort helped prune moment locales to shrink bundle
> Webpack analyzer

- package-lock.json
- package.json
- src/main.js
- src/store/actions.js
- src/store/index.js
- src/utils.js
- src/views/Clover.vue
Reverse ens lookup for addresses
Fixes #159
> reverse ens lookup for addresses

- src/components/CloverNameEditable.vue
- src/views/Clover.vue
- yarn.lock
#151 
– moved into it's own component + cleaned up Clover.vue
> Iss151 blank name use hash

- src/components/Pig.vue
- src/utils.js
- src/views/Field.vue
new cloverIsMonochrome() in utils.js
a little unclear if I integrated into Field.vue properly, inside that bottleneck task runner?
> Iss155 - remove monochromes from field + pig

- package.json
- src/components/Comments.vue
- src/components/Icons/ChatIcon.vue
- src/main.js
- src/store/actions.js
- src/style/global.css
- src/views/Clover.vue
- yarn.lock
Adds a new sub-component in `Clover.vue` that loads comments, listens for any new comments, and includes a form for posting them. 
Not sure if this is the most efficient way to manage the socket but it does work, also all comments are just loaded into the component data so we'll want to paginate at some point.
> View and post Comments on Clovers

- src/store/actions.js
- src/store/index.js
- src/store/mutations.js
> fixed mm sequence

- src/components/CloverItem--Card.vue
- src/utils.js
- src/views/Clover.vue
> Feed/Clover - show username / ens

- src/views/Clover.vue
- src/views/Trade.vue
Updates the notifications to accurately show how many shares were bought or sold, and triggers a read for amount of shares owned.
> RFT share amounts

- src/components/CloverItem--Card.vue
- src/components/CloverItem--Row.vue
- src/components/CloverNameEditable.vue
- src/store/actions.js
- src/style/global.css
- src/views/Account.vue
- src/views/Clover.vue
- src/views/Feed.vue
- src/views/Trade.vue
Also adds buy/sell all buttons where appropriate.
> Show market info in RFT cards

- package.json
- yarn.lock
> reduced 8MB

- src/assets/icons/arrow-down.svg
- src/assets/icons/arrow-up.svg
- src/assets/icons/chevron-down.svg
- src/assets/icons/chevron-up-white.svg
- src/assets/icons/chevron-up.svg
- src/assets/icons/sort-arrows.svg
- src/components/ActivityItem.vue
- src/components/AppHeader.vue
- src/components/CloverItem--Card.vue
- src/store/actions.js
- src/store/getters.js
- src/store/index.js
- src/store/mutations.js
- src/style/global.css
- src/style/helpers.css
- src/utils.js
- src/views/Activity.vue
- src/views/Clover.vue
Filtering and all sorts of other updates.
Closes #230, closes #239, closes #240
> log filtering, state management, and listeners

- src/components/ActivityItem.vue
> tweak some logs

- src/components/ActivityItem.vue
- src/components/CloverItem--Card.vue
- src/components/CloverList--Cards.vue
- src/components/Comments.vue
- src/components/Icons/HeartIcon.vue
- src/components/Messages.vue
- src/main.js
- src/router.js
- src/style/helpers-responsive.css
- src/style/helpers.css
- src/utils.js
- src/views/Clover.vue
- src/views/Feed.vue
- src/views/Field.vue
- src/views/KeepClover.vue
- src/views/Picks.vue
- src/views/User.vue
> Dev into master

- src/views/User.vue
> user balance

- src/store/actions.js
> auto close success notifications

- src/router.js
> closes 268

- src/components/Comments.vue
- src/router.js
- src/views/Clover.vue
> Add Clover/Comments route

- src/views/Clover.vue
- src/views/KeepClover.vue
> #259 success msg

- src/components/CloverItem--Card.vue
> bandaid #276

- src/components/ActivityItem.vue
- src/components/Comments.vue
- src/router.js
- src/style/helpers.css
- src/style/settings.css
- src/views/Activity.vue
> Iss251 activity log enhance

- src/App.vue
- src/components/AppHeader.vue
- src/components/CloverItem--Card.vue
- src/components/CloverItem--Row.vue
- src/components/PageNav.vue
- src/router.js
- src/store/actions.js
- src/store/getters.js
- src/store/index.js
- src/store/mutations.js
- src/style/helpers.css
- src/utils.js
- src/views/Activity.vue
- src/views/Clover.vue
- src/views/Feed.vue
- src/views/MyClovers.vue
- src/views/User.vue
No need to load all clovers and users at the start any more, api results are paginated and include user info at all times.
Will need to be published simultaneously with https://github.com/clovers-network/clovers-api/pull/7
> Paginate clovers

- src/components/Pig.vue
- src/store/actions.js
- src/store/getters.js
- src/store/mutations.js
- src/views/Activity.vue
- src/views/Clover.vue
- src/views/KeepClover.vue
- src/views/Trade.vue
Calculations were wrong after updating api format
> Fix user balances

- src/components/ActivityItem.vue
- src/components/Comments.vue
- src/main.js
- src/store/actions.js
Closes #293.
Comments are loaded as you scroll up ✨
> Clover activity, and paginated comments

- src/components/MoreInformation.vue
- src/router.js
- src/views/Account.vue
- src/views/Feed.vue
- src/views/Field.vue
- src/views/KeepClover.vue
- src/views/Learn/Learn__Section--Intro.vue
- src/views/Picks.vue
> More Information

- src/components/PagedAlbums.vue
Guess this just wasn't finished before, rather than deliberately disabled @okwme?
> Fix album pagination
